# Generated by Django 5.2.3 on 2025-06-22 19:03

import default_site.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('basic', models.CharField(max_length=500)),
                ('extended', models.CharField(max_length=500)),
                ('id_for_html', models.CharField(max_length=50)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientsAndGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(blank=True, max_length=300, null=True)),
                ('clientLogoURL', models.ImageField(blank=True, max_length=150, upload_to=default_site.models.upload_to_image_link_logo)),
                ('clientHeroURL', models.ImageField(blank=True, max_length=150, upload_to=default_site.models.upload_to_image_link_logo)),
                ('clientLongDescription', models.CharField(blank=True, max_length=3000, null=True)),
                ('clientShortDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('group', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('colorModifier', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('basic', models.CharField(max_length=500)),
                ('extended', models.CharField(max_length=500)),
                ('id_for_html', models.CharField(max_length=50)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('displayorder', models.IntegerField()),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvolvingFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('basic', models.CharField(max_length=500)),
                ('extended', models.CharField(max_length=500)),
                ('id_for_html', models.CharField(max_length=50)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportantOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('longdescription', models.CharField(max_length=5000)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportantOptionsMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('longdescription', models.CharField(max_length=5000)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestTickets',
            fields=[
                ('requestID', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('new', 'new'), ('in-progress', 'in-progress'), ('archived', 'archived'), ('priority_1', 'priority_1'), ('priority_2', 'priority_2'), ('priority_3', 'priority_3')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('basic', models.CharField(max_length=500)),
                ('extended', models.CharField(max_length=500)),
                ('id_for_html', models.CharField(max_length=50)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('fontawesome', models.CharField(max_length=50)),
                ('link', models.CharField(blank='true', max_length=150, null='true')),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientGalleryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.ImageField(blank=True, max_length=150, upload_to=default_site.models.upload_to_image_link_graphic)),
                ('imageTwoURL', models.ImageField(blank=True, max_length=150, upload_to=default_site.models.upload_to_image_link_graphic)),
                ('videoURL', models.CharField(blank=True, max_length=300, null=True)),
                ('sectionTitle', models.CharField(blank=True, max_length=300, null=True)),
                ('sectionType', models.CharField(blank=True, max_length=300, null=True)),
                ('shortDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('longDescription', models.CharField(blank=True, max_length=3000, null=True)),
                ('order', models.IntegerField()),
                ('display', models.BooleanField(default=True)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_site.clientsandgroups')),
            ],
        ),
        migrations.CreateModel(
            name='FormQuestions',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('question', models.CharField(max_length=200)),
                ('blockclass', models.CharField(blank=True, max_length=50, null=True)),
                ('labelclass', models.CharField(blank=True, max_length=50, null=True)),
                ('inputclass', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, choices=[('button', 'button'), ('checkbox', 'checkbox'), ('color', 'color'), ('date', 'date'), ('datetime-local', 'datetime-local'), ('email', 'email'), ('file', 'file'), ('hidden', 'hidden'), ('image', 'image'), ('month', 'month'), ('number', 'number'), ('password', 'password'), ('radio', 'radio'), ('range', 'range'), ('reset', 'reset'), ('search', 'search'), ('tel', 'tel'), ('text', 'text'), ('time', 'time'), ('url', 'url'), ('week', 'week'), ('select', 'select'), ('textarea', 'textarea')], max_length=50, null=True)),
                ('multiselection', models.BooleanField(default=False)),
                ('charlimit', models.IntegerField(blank=True, default=500, null=True)),
                ('placeholdertext', models.CharField(blank=True, max_length=500, null=True)),
                ('required', models.BooleanField(default=True)),
                ('contactoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_site.contactoptions')),
            ],
        ),
        migrations.CreateModel(
            name='QAndA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=2000)),
                ('date_created', models.DateTimeField()),
                ('order', models.IntegerField()),
                ('relatedcontactoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_site.contactoptions')),
                ('requestID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='default_site.requesttickets')),
            ],
        ),
        migrations.CreateModel(
            name='Selectoptions',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('optionname', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('formquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_site.formquestions')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('CustomerID', models.BigAutoField(primary_key=True, serialize=False)),
                ('House_number_or_name', models.CharField(blank=True, max_length=150, null=True)),
                ('Address_line_one', models.CharField(blank=True, max_length=150, null=True)),
                ('Town', models.CharField(blank=True, max_length=150, null=True)),
                ('County', models.CharField(blank=True, max_length=99, null=True)),
                ('Uk_resident', models.BooleanField(default=True)),
                ('Postcode', models.CharField(blank=True, max_length=30, null=True)),
                ('Birth_date', models.DateField(blank=True, null=True)),
                ('First_name', models.CharField(blank=True, max_length=40, null=True)),
                ('Last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('Phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('Contact_via_email', models.BooleanField(default=False)),
                ('Contact_via_phone', models.BooleanField(default=False)),
                ('Contact_via_text', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='requesttickets',
            name='customerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='default_site.userprofile'),
        ),
    ]
