# Generated by Django 4.1 on 2022-09-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0003_socials'),
    ]

    operations = [
        migrations.CreateModel(
            name='importantOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('longdescription', models.CharField(max_length=1000)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
    ]
