# Generated by Django 4.1 on 2022-09-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0004_importantoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantoptions',
            name='icon',
            field=models.CharField(default='dave', max_length=100),
            preserve_default=False,
        ),
    ]
