# Generated by Django 4.1 on 2022-09-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0005_importantoptions_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantoptions',
            name='longdescription',
            field=models.CharField(max_length=5000),
        ),
    ]
