# Generated by Django 4.1.6 on 2023-02-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0006_alter_importantoptions_longdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('link', models.CharField(blank=True, max_length=150, null=True)),
                ('display', models.BooleanField(default=True)),
                ('full', models.BooleanField(default=False)),
            ],
        ),
    ]
