# Generated by Django 4.1.6 on 2023-02-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0007_contactoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoptions',
            name='formQ1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ5',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactoptions',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
