# Generated by Django 4.1.6 on 2023-02-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0008_contactoptions_formq1_contactoptions_formq2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoptions',
            name='htmlId',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
