# Generated by Django 4.1.6 on 2023-02-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0009_contactoptions_htmlid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoptions',
            name='formQ1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactoptions',
            name='formQ2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactoptions',
            name='formQ3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactoptions',
            name='formQ4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactoptions',
            name='formQ5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
