# Generated by Django 4.1.6 on 2023-02-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0010_alter_contactoptions_formq1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=40)),
                ('Lastname', models.CharField(max_length=40)),
                ('EmailAddress', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ10CharLimit',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ10Class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ10number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ10type',
            field=models.CharField(blank=True, default='text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ1CharLimit',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ1Class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ1number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ1type',
            field=models.CharField(blank=True, default='text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ2CharLimit',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ2Class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ2number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ2type',
            field=models.CharField(blank=True, default='text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ3CharLimit',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ3Class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ3number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ3type',
            field=models.CharField(blank=True, default='text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ4CharLimit',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ4Class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ4number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ4type',
            field=models.CharField(blank=True, default='text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ5CharLimit',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ5Class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ5number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ5type',
            field=models.CharField(blank=True, default='text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ6CharLimit',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ6Class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ6number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ6type',
            field=models.CharField(blank=True, default='text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ7CharLimit',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ7Class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ7number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ7type',
            field=models.CharField(blank=True, default='text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ8CharLimit',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ8Class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ8number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ8type',
            field=models.CharField(blank=True, default='text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ9CharLimit',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ9Class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ9number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='contactoptions',
            name='formQ9type',
            field=models.CharField(blank=True, default='text', max_length=50, null=True),
        ),
    ]
