# Generated by Django 4.1.6 on 2023-02-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0011_customer_contactoptions_formq10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoptions',
            name='formQ10number',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='contactoptions',
            name='formQ2number',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='contactoptions',
            name='formQ3number',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='contactoptions',
            name='formQ4number',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='contactoptions',
            name='formQ5number',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='contactoptions',
            name='formQ6number',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
        migrations.AlterField(
            model_name='contactoptions',
            name='formQ7number',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name='contactoptions',
            name='formQ8number',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='contactoptions',
            name='formQ9number',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
    ]
