# Generated by Django 4.1.6 on 2023-02-18 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0015_remove_formquestions_contactoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htmlId', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='formquestions',
            name='contactoption',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='default_site.contactoptions'),
            preserve_default=False,
        ),
    ]
