# Generated by Django 4.1.6 on 2023-02-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0016_contactoptions_formquestions_contactoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactoptions',
            name='htmlId',
        ),
    ]
