# Generated by Django 4.1.6 on 2023-02-18 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0019_formquestions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormQuestions',
        ),
    ]
