# Generated by Django 4.1.6 on 2023-02-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0021_formquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestions',
            name='selectoptions',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
