# Generated by Django 4.1.6 on 2023-02-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0023_formquestions_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestions',
            name='type',
            field=models.CharField(blank=True, choices=[('BTN', 'button'), ('CKB', 'checkbox'), ('COL', 'color'), ('DAT', 'date'), ('DTL', 'datetime-local'), ('BTN', 'email'), ('FIL', 'file'), ('HDN', 'hidden'), ('IMG', 'image'), ('MON', 'month'), ('NUM', 'number'), ('PWD', 'password'), ('RAD', 'radio'), ('RNG', 'range'), ('RST', 'reset'), ('SRC', 'search'), ('TEL', 'tel'), ('TXT', 'text'), ('TIM', 'time'), ('URL', 'url'), ('WEK', 'week'), ('SEL', 'select')], max_length=50, null=True),
        ),
    ]
