# Generated by Django 4.1.6 on 2023-02-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0024_alter_formquestions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoptions',
            name='displayorder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
