# Generated by Django 4.1.6 on 2023-02-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0025_contactoptions_displayorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoptions',
            name='displayorder',
            field=models.IntegerField(),
        ),
    ]
