# Generated by Django 4.1.6 on 2023-02-19 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0026_alter_contactoptions_displayorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
