# Generated by Django 4.1.6 on 2023-02-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0028_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoptions',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
