# Generated by Django 4.1.6 on 2023-02-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0029_contactoptions_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestions',
            name='Placeholdertext',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='formquestions',
            name='Required',
            field=models.BooleanField(default=True),
        ),
    ]
