# Generated by Django 4.1.6 on 2023-02-20 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0032_rename_equired_formquestions_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formquestions',
            name='selectoptions',
        ),
        migrations.CreateModel(
            name='Selectoptions',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('optionName', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('contactoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_site.contactoptions')),
            ],
        ),
    ]
