# Generated by Django 4.1.6 on 2023-02-20 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0033_remove_formquestions_selectoptions_selectoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectoptions',
            name='contactoption',
        ),
        migrations.AddField(
            model_name='selectoptions',
            name='formquestion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='default_site.formquestions'),
            preserve_default=False,
        ),
    ]
