# Generated by Django 4.1.6 on 2023-03-11 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('default_site', '0035_rename_optionname_selectoptions_optionname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAndA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=2000)),
                ('date_created', models.DateField()),
                ('contactoption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='default_site.contactoptions')),
            ],
        ),
        migrations.CreateModel(
            name='RequestTickets',
            fields=[
                ('requestID', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('CustomerID', models.BigAutoField(primary_key=True, serialize=False)),
                ('address_line_one', models.CharField(blank=True, max_length=150, null=True)),
                ('address_line_two', models.CharField(blank=True, max_length=150, null=True)),
                ('address_line_three', models.CharField(blank=True, max_length=99, null=True)),
                ('uk_resident', models.BooleanField(default=True)),
                ('postcode', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('First_name', models.CharField(blank=True, max_length=40, null=True)),
                ('Last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('Phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='requesttickets',
            name='customerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='default_site.userprofile'),
        ),
        migrations.AddField(
            model_name='qanda',
            name='requestID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='default_site.userprofile'),
        ),
    ]
