# Generated by Django 4.1.6 on 2023-03-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0036_qanda_requesttickets_userprofile_delete_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qanda',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='requesttickets',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
