# Generated by Django 4.1.6 on 2023-03-12 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0037_alter_qanda_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qanda',
            old_name='contactoption',
            new_name='relatedcontactoption',
        ),
    ]
