# Generated by Django 4.1.6 on 2023-03-12 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0039_alter_qanda_relatedcontactoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qanda',
            name='requestID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='default_site.requesttickets'),
        ),
    ]
