# Generated by Django 4.1.6 on 2023-04-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0040_alter_qanda_requestid'),
    ]

    operations = [
        migrations.AddField(
            model_name='qanda',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
