# Generated by Django 4.1.6 on 2023-07-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0044_rename_address_line_one_userprofile_address_line_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Contact_via_text',
            field=models.BooleanField(default=False),
        ),
    ]
