# Generated by Django 4.1.6 on 2025-05-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0045_userprofile_contact_via_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantOptionsMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('longdescription', models.CharField(max_length=5000)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
    ]
