# Generated by Django 4.1.6 on 2025-05-14 22:09

import default_site.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0046_importantoptionsmarketing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsAndGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(blank=True, max_length=300, null=True)),
                ('clientLogoURL', models.ImageField(blank=True, max_length=150, upload_to=default_site.models.upload_to_image_link_logo)),
                ('clientLongDescription', models.CharField(blank=True, max_length=3000, null=True)),
                ('clientShortDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('group', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientGalleryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.ImageField(blank=True, max_length=150, upload_to=default_site.models.upload_to_image_link_graphic)),
                ('videoURL', models.CharField(blank=True, max_length=300, null=True)),
                ('shortDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('longDescription', models.CharField(blank=True, max_length=3000, null=True)),
                ('order', models.IntegerField()),
                ('display', models.BooleanField(default=True)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_site.clientsandgroups')),
            ],
        ),
    ]
