# Generated by Django 4.1.6 on 2025-05-15 01:08

import default_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0047_clientsandgroups_clientgallerypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsandgroups',
            name='clientHeroURL',
            field=models.ImageField(blank=True, max_length=150, upload_to=default_site.models.upload_to_image_link_logo),
        ),
    ]
