# Generated by Django 4.1.6 on 2025-05-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0048_clientsandgroups_clientherourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientgallerypage',
            name='sectionTitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='clientgallerypage',
            name='sectionType',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
