# Generated by Django 4.1.6 on 2025-05-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0049_clientgallerypage_sectiontitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsandgroups',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
