# Generated by Django 4.1.6 on 2025-05-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0050_clientsandgroups_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsandgroups',
            name='colorModifier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
