# Generated by Django 4.1.6 on 2025-06-01 20:27

import copilot.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('default_site', '0053_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(blank=True, max_length=300, null=True)),
                ('projectLogoURL', models.ImageField(blank=True, max_length=150, upload_to=copilot.models.upload_to_image_link_logo)),
                ('projectHeroURL', models.ImageField(blank=True, max_length=150, upload_to=copilot.models.upload_to_image_link_hero)),
                ('projectLongDescription', models.CharField(blank=True, max_length=3000, null=True)),
                ('projectShortDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('marketing', models.BooleanField(default=False)),
                ('website', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('colorOne', models.CharField(blank=True, max_length=200, null=True)),
                ('colorModifierOne', models.CharField(blank=True, max_length=200, null=True)),
                ('colorTwo', models.CharField(blank=True, max_length=200, null=True)),
                ('colorModifierTwo', models.CharField(blank=True, max_length=200, null=True)),
                ('colorThree', models.CharField(blank=True, max_length=200, null=True)),
                ('colorModifierThree', models.CharField(blank=True, max_length=200, null=True)),
                ('colorFour', models.CharField(blank=True, max_length=200, null=True)),
                ('colorModifierFour', models.CharField(blank=True, max_length=200, null=True)),
                ('colorFive', models.CharField(blank=True, max_length=200, null=True)),
                ('colorModifierFive', models.CharField(blank=True, max_length=200, null=True)),
                ('LinkedClient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='default_site.clientsandgroups')),
                ('LinkedRequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='default_site.requesttickets')),
                ('LinkedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='default_site.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copilot.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPageSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionTitle', models.CharField(blank=True, max_length=300, null=True)),
                ('sectionType', models.CharField(blank=True, max_length=300, null=True)),
                ('shortDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('longDescription', models.CharField(blank=True, max_length=3000, null=True)),
                ('order', models.IntegerField()),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(blank=True, max_length=300, null=True)),
                ('imageURL', models.ImageField(blank=True, max_length=170, upload_to=copilot.models.upload_to_image_link_projectImage)),
                ('videoURL', models.FileField(blank=True, max_length=150, upload_to=copilot.models.upload_to_video_link)),
                ('dateUploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('projectPage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copilot.projectpage')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedMediaMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(blank=True, max_length=300, null=True)),
                ('dateTaken', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='copilot.tag')),
                ('uploadedMediaLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copilot.uploadedmedia')),
            ],
        ),
        migrations.CreateModel(
            name='SectionComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='copilot.sectioncomments')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='copilot.projectpagesections')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectpagesections',
            name='uploadedMedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copilot.uploadedmedia'),
        ),
    ]
