# Generated by Django 4.1.6 on 2025-06-01 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedmedia',
            name='projectPage',
        ),
        migrations.AddField(
            model_name='uploadedmedia',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='copilot.project'),
            preserve_default=False,
        ),
    ]
