# Generated by Django 4.1.6 on 2025-06-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0002_remove_uploadedmedia_projectpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedmedia',
            name='backgroundColor',
            field=models.CharField(default='white', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedmedia',
            name='backgroundColorModifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
