# Generated by Django 4.1.6 on 2025-06-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0003_uploadedmedia_backgroundcolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedmedia',
            name='textColor',
            field=models.CharField(default='white', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedmedia',
            name='textColorModifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedmedia',
            name='backgroundColor',
            field=models.CharField(default='black', max_length=100),
        ),
    ]
