# Generated by Django 4.1.6 on 2025-06-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0004_uploadedmedia_textcolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='backgroundColor',
            field=models.CharField(default='black', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='backgroundColorModifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='textColor',
            field=models.CharField(default='white-text', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='textColorModifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='titleBackgroundColor',
            field=models.CharField(default='black', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='titleBackgroundColorModifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='titleColor',
            field=models.CharField(default='white-text', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='titleTextColorModifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectpagesections',
            name='backgroundColor',
            field=models.CharField(default='black', max_length=100),
        ),
        migrations.AddField(
            model_name='projectpagesections',
            name='backgroundColorModifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectpagesections',
            name='textColor',
            field=models.CharField(default='white-text', max_length=100),
        ),
        migrations.AddField(
            model_name='projectpagesections',
            name='textColorModifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectpagesections',
            name='titleBackgroundColor',
            field=models.CharField(default='black', max_length=100),
        ),
        migrations.AddField(
            model_name='projectpagesections',
            name='titleBackgroundColorModifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectpagesections',
            name='titleColor',
            field=models.CharField(default='white-text', max_length=100),
        ),
        migrations.AddField(
            model_name='projectpagesections',
            name='titleTextColorModifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedmedia',
            name='textColor',
            field=models.CharField(default='white-text', max_length=100),
        ),
    ]
