# Generated by Django 4.1.6 on 2025-06-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0005_project_backgroundcolor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpagesections',
            name='uploadedMedia',
        ),
        migrations.AddField(
            model_name='projectpagesections',
            name='uploadedMedia',
            field=models.ManyToManyField(to='copilot.uploadedmedia'),
        ),
    ]
