# Generated by Django 4.1.6 on 2025-06-03 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0006_remove_projectpagesections_uploadedmedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpagesections',
            name='projectPage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='copilot.projectpage'),
            preserve_default=False,
        ),
    ]
