# Generated by Django 4.1.6 on 2025-06-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0053_alter_userprofile_user'),
        ('copilot', '0008_projectpagesections_borderbackgroundcolor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='LinkedUser',
        ),
        migrations.AddField(
            model_name='project',
            name='linkedUsers',
            field=models.ManyToManyField(blank=True, related_name='projects', to='default_site.userprofile'),
        ),
        migrations.AlterField(
            model_name='projectpagesections',
            name='uploadedMedia',
            field=models.ManyToManyField(blank=True, to='copilot.uploadedmedia'),
        ),
    ]
