# Generated by Django 4.1.6 on 2023-03-13 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('default_site', '0040_alter_qanda_requestid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField()),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='default_site.userprofile')),
            ],
        ),
    ]
