# Generated by Django 5.2.3 on 2025-06-22 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('default_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amounttopay', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField()),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='default_site.userprofile')),
            ],
        ),
    ]
