# Generated by Django 4.1.6 on 2023-03-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amounttopay',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
