# Generated by Django 5.2.3 on 2025-06-22 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('default_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('moduleID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('cost', models.CharField(max_length=50)),
                ('devtimedays', models.IntegerField(default=True)),
                ('available', models.BooleanField(default=False)),
                ('comingsoon', models.BooleanField(default=False)),
                ('releasedate', models.DateField(blank=True, null=True)),
                ('readmorelink', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModulesMarketing',
            fields=[
                ('moduleID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('cost', models.CharField(max_length=50)),
                ('devtimedays', models.IntegerField(default=True)),
                ('available', models.BooleanField(default=False)),
                ('comingsoon', models.BooleanField(default=False)),
                ('releasedate', models.DateField(blank=True, null=True)),
                ('readmorelink', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('pricesID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.IntegerField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricesMarketing',
            fields=[
                ('pricesID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.IntegerField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedQuotes',
            fields=[
                ('QuoteID', models.BigAutoField(primary_key=True, serialize=False)),
                ('SelectedModules', models.CharField(blank=True, max_length=50, null=True)),
                ('JourneyPage', models.CharField(max_length=50)),
                ('AmountOfPages', models.IntegerField(blank=True, null=True)),
                ('AmountOfProducts', models.IntegerField(blank=True, null=True)),
                ('AmountOfSubscribers', models.IntegerField(blank=True, null=True)),
                ('AmountOfTraffic', models.IntegerField(blank=True, null=True)),
                ('AmountOfData', models.IntegerField(blank=True, null=True)),
                ('CostOfPages', models.IntegerField(blank=True, null=True)),
                ('CostOfProducts', models.IntegerField(blank=True, null=True)),
                ('CostOfSubscribers', models.IntegerField(blank=True, null=True)),
                ('CostOfTraffic', models.IntegerField(blank=True, null=True)),
                ('CostOfData', models.IntegerField(blank=True, null=True)),
                ('Deposit', models.IntegerField(blank=True, null=True)),
                ('Total', models.IntegerField(blank=True, null=True)),
                ('DateOfQuote', models.DateField()),
                ('NameOfQuote', models.CharField(max_length=50)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='default_site.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SavedQuotesMarketing',
            fields=[
                ('QuoteID', models.BigAutoField(primary_key=True, serialize=False)),
                ('SelectedModules', models.CharField(blank=True, max_length=50, null=True)),
                ('JourneyPage', models.CharField(max_length=50)),
                ('AmountOfPages', models.IntegerField(blank=True, null=True)),
                ('AmountOfProducts', models.IntegerField(blank=True, null=True)),
                ('AmountOfSubscribers', models.IntegerField(blank=True, null=True)),
                ('AmountOfTraffic', models.IntegerField(blank=True, null=True)),
                ('AmountOfData', models.IntegerField(blank=True, null=True)),
                ('CostOfPages', models.IntegerField(blank=True, null=True)),
                ('CostOfProducts', models.IntegerField(blank=True, null=True)),
                ('CostOfSubscribers', models.IntegerField(blank=True, null=True)),
                ('CostOfTraffic', models.IntegerField(blank=True, null=True)),
                ('CostOfData', models.IntegerField(blank=True, null=True)),
                ('Deposit', models.IntegerField(blank=True, null=True)),
                ('Total', models.IntegerField(blank=True, null=True)),
                ('DateOfQuote', models.DateField()),
                ('NameOfQuote', models.CharField(max_length=50)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='default_site.userprofile')),
            ],
        ),
    ]
