# Generated by Django 4.1.6 on 2023-03-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('moduleID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('cost', models.CharField(max_length=50)),
                ('devtimedays', models.IntegerField(default=True)),
                ('available', models.BooleanField(default=False)),
                ('comingsoon', models.BooleanField(default=False)),
                ('releasedate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
