# Generated by Django 4.1.6 on 2023-03-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='readmorelink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
