# Generated by Django 4.1.6 on 2023-03-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_calculator', '0002_modules_readmorelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('pricesID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.IntegerField(default=True)),
            ],
        ),
    ]
