# Generated by Django 4.1.6 on 2023-06-29 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default_site', '0042_requesttickets_status'),
        ('price_calculator', '0003_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuotes',
            fields=[
                ('QuoteID', models.BigAutoField(primary_key=True, serialize=False)),
                ('SelectedModules', models.CharField(blank=True, max_length=50, null=True)),
                ('JourneyPage', models.CharField(max_length=50)),
                ('AmountOfPages', models.IntegerField(blank=True, null=True)),
                ('AmountOfProducts', models.IntegerField(blank=True, null=True)),
                ('AmountOfSubscribers', models.IntegerField(blank=True, null=True)),
                ('AmountOfTraffic', models.IntegerField(blank=True, null=True)),
                ('AmountOfData', models.IntegerField(blank=True, null=True)),
                ('CostOfPages', models.IntegerField(blank=True, null=True)),
                ('CostOfProducts', models.IntegerField(blank=True, null=True)),
                ('CostOfSubscribers', models.IntegerField(blank=True, null=True)),
                ('CostOfTraffic', models.IntegerField(blank=True, null=True)),
                ('CostOfData', models.IntegerField(blank=True, null=True)),
                ('Deposit', models.IntegerField(blank=True, null=True)),
                ('Total', models.IntegerField(blank=True, null=True)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='default_site.userprofile')),
            ],
        ),
    ]
