# Generated by Django 4.1.6 on 2023-06-29 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('price_calculator', '0004_savedquotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedquotes',
            name='DateOfQuote',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedquotes',
            name='NameOfQuote',
            field=models.CharField(default='no name', max_length=50),
            preserve_default=False,
        ),
    ]
